### ISSUE TITLE
Long-time user having issues

### ISSUE THREAD

**Issue by SETXTyleryo** [JLaferri/ChallongeMatchDisplay#5]
Hello. I have been using Challonge Match Display since at least 2015-16 or so. We took a break from events for the pandemic and are now hopping into them and wanting to use this again. However I simply cannot get the program to run without receiving this error:

To run this application, you must install .NET.

The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found.

Would you like to download it now?

Screenshot: https://i.imgur.com/qv65pmu.png
![qv65pmu](https://user-images.githubusercontent.com/112730906/188235082-8cacc4c9-caf9-4c3b-85d2-007685e199a5.png)

However, after following the link, installing, and rebooting the computer, I come back to the same error. I am not a programmer by any means, so there is a strong change its user error somehow. Any advice would be welcome. Thank you for your time and work on this.

**Comment by gazugafan** [comment]
Are you sure you have .net 5.0.0 installed? Maybe you installed the latest version instead? I'd double-check that, and maybe try uninstalling/reinstalling .net.

Also, I've secretly been working on a web-based version of this ***the whole time***. It's ALMOST ready for a full public release. Hopefully by the end of the year. But until then, it's absolutely usable--I've been using it exclusively for the last 4 years or so. If anyone wants to try it out, it's at...
https://round.one

Or if you just want to see a quick example of a real tournament from awhile ago...
https://round.one/tournament/jnqbt

Just let me know if you create an account and I'll flag it for full VIP access (otherwise you won't have permission to create tournaments for now).

It's basically a complete replacement for challonge, with station management built-in. To get scores, player names, etc automatically updating in a txt or xml file, you just have to link your dropbox account. Then, you specify a station as a "streaming" station, and the player names/scores on that station will automatically sync to files in your dropbox account. Install dropbox wherever you're streaming from to access those files. 

Or, just open the tournament in a browser on another computer/monitor to display the station assignments for everyone to see. Easy-peasy! Hope you check it out 😁

**Comment by Abrahamh08** [comment]
> Are you sure you have .net 5.0.0 installed? Maybe you installed the latest version instead? I'd double-check that, and maybe try uninstalling/reinstalling .net.
> 
> Also, I've secretly been working on a web-based version of this _**the whole time**_. It's ALMOST ready for a full public release. Hopefully by the end of the year. But until then, it's absolutely usable--I've been using it exclusively for the last 4 years or so. If anyone wants to try it out, it's at... https://round.one
> 
> Or if you just want to see a quick example of a real tournament from awhile ago... https://round.one/tournament/jnqbt
> 
> Just let me know if you create an account and I'll flag it for full VIP access (otherwise you won't have permission to create tournaments for now).
> 
> It's basically a complete replacement for challonge, with station management built-in. To get scores, player names, etc automatically updating in a txt or xml file, you just have to link your dropbox account. Then, you specify a station as a "streaming" station, and the player names/scores on that station will automatically sync to files in your dropbox account. Install dropbox wherever you're streaming from to access those files.
> 
> Or, just open the tournament in a browser on another computer/monitor to display the station assignments for everyone to see. Easy-peasy! Hope you check it out 😁

Sounds interesting, thanks for sharing. But 5.0.0 is pretty old, so I will push a commit (if I haven't already done so) and make a release that uses NET 6 or 7. That also might fix your issue.

**Comment by SETXTyleryo** [comment]
I have tried on different machines, and have had others try, yet we all get the same error after installing 5.0.0.  I'll check out round.one, but I would ultimately like to keep using Challonge with this for the time being. Thank you guys for looking into it.

**Comment by Abrahamh08** [comment]
> I have tried on different machines, and have had others try, yet we all get the same error after installing 5.0.0. I'll check out round.one, but I would ultimately like to keep using Challonge with this for the time being. Thank you guys for looking into it.

Make sure to install the ASP.NET Core runtime, not just the .NET Core runtime: https://dotnet.microsoft.com/en-us/download/dotnet/5.0#:~:text=The%20ASP.NET%20Core%20Runtime,NET%20Runtime%20and%20IIS%20support.

Note that when I get back to my house in 7 days, I will be upgrading the project to .NET Core 6. It will then be required to install the NET Core 6 and ASP.NET Core 6 runtime. You may install them ahead of time, as they are backwards compatible (you may install both at https://dotnet.microsoft.com/en-us/download/dotnet/6.0). Let me know if this works for you.

**Comment by SETXTyleryo** [comment]
That did up being the solution. Thank you guys for taking time out of your day to help with this. This program does help with things a lot. I will keep an eye out for the update.

**Comment by Abrahamh08** [comment]
> That did up being the solution. Thank you guys for taking time out of your day to help with this. This program does help with things a lot. I will keep an eye out for the update.

Awesome. There are some good things coming in the update as well (minor fixes, standings), I'll mark it as a prerelease.
